### ISSUE TITLE
Balanced tree problem AVL tree 

### ISSUE THREAD

**Issue by arpit1997** [algobook/Algo_Ds_Notes#288]
This issue is in reference to #280 which is the same kind of problem of balancing trees. **Adelson-Velskii and Landis trees** are called to be more robust than red black trees. The good thing about avl is that it can contain difference og height 1 between two branches.
ping me if anyone wants to contribute to this issue.
:smile: 
:smile:

**Comment by samsondstl** [comment]
I could contribute C++ and Java, if desired.

**Comment by Aniket965** [comment]
create pr
